version: "3" 
services:
  # Database
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - yasser
  #Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    volumes: ["./wp-content:/var/www/html/wp-content"]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DEBUG: 1
    ports:
      - 80:80
      - 443:443
    networks:
      - yasser
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - yasser
networks:
  yasser:
volumes:
  db_data: